version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: stockai_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: stockai
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: stockai2025
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
